export const COLLEGE_NAMES = [
  "FASCM-Faculty of Arts, Science, Commerce and Management",
  "FOADP-Faculty of Architecture, Designing and Planning",
  "FOE-Faculty of Engineering",
  "FOP-Faculty of Pharmacy",
  "KPC-Karpagam Polytechnic College",
  "KAHE",
];

export const STAFF_ONLY_COLLEGE = "KAHE";

export const POLYTECHNIC_COLLEGE = "KPC-Karpagam Polytechnic College";

// Diploma courses — only for Karpagam Polytechnic College (KPC)
export const POLYTECHNIC_COURSES = [
  "DME",
  "DME & Tool & Die",
  "DCE",
  "DCOE",
  "DECE",
  "DEEE",
  "DIT",
  "DAE",
];

// Courses available for all other colleges (non-polytechnic)
export const NON_POLYTECHNIC_COURSES = [
  "Bachelor of Architecture",
  "Bachelor of Arts",
  "Bachelor of Business Administration",
  "Bachelor of Commerce",
  "Bachelor of Computer Applications",
  "Bachelor of Design",
  "Bachelor of Engineering",
  "Bachelor of Pharmacy",
  "Bachelor of Philosophy",
  "Bachelor of Science",
  "Bachelor of Technology",
  "Master of Architecture",
  "Master of Building and Engineering Management",
  "Master of Business Administration",
  "Master of Commerce",
  "Master of Computer Applications",
  "Master of Engineering",
  "Master of Pharmacy",
  "Master of Philosophy",
  "Master of Planning",
  "Master of Science",
  "Master of Social Work",
  "Pharm. D",
  "Ph.D",
];

// All courses combined (kept for backward compatibility)
export const COURSES = [...NON_POLYTECHNIC_COURSES, ...POLYTECHNIC_COURSES];

/**
 * Returns the appropriate course list based on the selected college.
 * - KPC (Polytechnic) → only diploma courses
 * - All other colleges → non-polytechnic courses
 * - No college selected → all courses
 */
export const getCoursesForCollege = (collegeName) => {
  if (!collegeName) return COURSES;
  if (collegeName === POLYTECHNIC_COLLEGE) return POLYTECHNIC_COURSES;
  return NON_POLYTECHNIC_COURSES;
};

export const COURSE_BRANCH_MAPPING = {
  "Bachelor of Architecture": ["General"],
  "Bachelor of Arts": ["English Literature", "General"],
  "Bachelor of Business Administration": [
    "BBA",
    "Business Process Services",
    "General",
  ],
  "Bachelor of Commerce": [
    "FA",
    "B. Com",
    "B. Com CA",
    "Business Process Services",
    "IAF",
    "Information Technology",
    "Professional Accounting",
    // "Computer Application",
    "Computer Science",
  ],
  "Bachelor of Computer Applications": ["Computer Application", "General"],
  "Bachelor of Design": ["General", "Interior Design"],
  "Bachelor of Engineering": [
    "Aeronautical Engineering",
    "Aerospace Engineering",
    "Automobile Engineering",
    "Bio Medical Engineering",
    "Chemical Engineering",
    "Civil Engineering",
    "Computer Science and Design",
    "Computer Science Engineering",
    "Computer Science Engineering(Cyber)",
    "Electrical & Electronics Engineering",
    "Electronics & Communication Engineering",
    "Food Technology",
    "Information Technology",
    "Mechanical Engineering",
  ],
  "Bachelor of Pharmacy": ["B. Pharm"],
  "Bachelor of Science": [
    "Artificial Intelligence / Data Science",
    "Bio Chemistry",
    "Bio Informatics",
    "Bio Technology",
    "Catering Science and Hotel Management",
    "Chemistry",
    "Cognitive systems",
    "Computer Science",
    "Computer Technology",
    "Cyber Security",
    "General",
    "Information Technology",
    "Mathematics",
    "Microbiology",
    "Physics",
  ],
  "Bachelor of Technology": [
    "Aeronautical Engineering",
    "Aerospace Engineering",
    "Artificial Intelligence / Data Science",
    "Automobile Engineering",
    "Bio Medical Engineering",
    "Bio Technology",
    "Chemical Engineering",
    "Civil Engineering",
    "Computer Science Engineering",
    "Electrical & Electronics Engineering",
    "Electronics & Communication Engineering",
    "Food Technology",
    "Mechanical Engineering",
  ],
  "Master of Architecture": ["General"],
  "Master of Building and Engineering Management": ["General"],
  "Master of Business Administration": ["Business Process Services", "General", "MBA"],
  "Master of Commerce": ["General", "Professional Accounting", "M. Com"],
  "Master of Computer Applications": ["Computer Application", "General"],
  "Master of Engineering": [
    "Aeronautical Engineering",
    "Aerospace Engineering",
    "Automobile Engineering",
    "Bio Medical Engineering",
    "Chemical Engineering",
    "Civil Engineering",
    "Computer Science Engineering",
    "Electrical & Electronics Engineering",
    "Electronics & Communication Engineering",
    "Food Technology",
    "Information Technology",
    "Mechanical Engineering",
    "Mechanical Engineering (CAD/CAM Robotics)",
    "Power Electronics and Drives",
    "Power System Engineering",
    "Structural Engineering",
    "Structural Engineering (Part Time)",
    "VLSI",
    "Water Resources And Environmental Engineering",
  ],
  "Master of Pharmacy": ["M. Pharm (Pharmaceutics)", "M. Pharm (Analysis)", "M. Pharm (Chemistry)"],
  "Master of Philosophy": ["General"],
  "Master of Planning": ["General"],
  "Master of Science": [
    "Bio Chemistry",
    "Bio Informatics",
    "Bio Technology",
    "Catering Science and Hotel Management",
    "Chemistry",
    "Cognitive Science",
    "Computer Science",
    "Computer Technology",
    "General",
    "Mathematics",
    "Microbiology",
    "Physics",
  ],
  "Master of Social Work": ["General"],
  "DME": ["General"],
  "DME & Tool & Die": ["General"],
  "DCE": ["General"],
  "DCOE": ["General"],
  "DECE": ["General"],
  "DEEE": ["General"],
  "DIT": ["General"],
  "DAE": ["General"],
  "Pharm. D": ["General"],
  "Ph.D": [
    "Aeronautical Engineering",
    "Aerospace Engineering",
    "Artificial Intelligence/Data Science",
    "Automobile Engineering",
    "Bio Chemistry",
    "Bio Informatics",
    "Bio Medical Engineering",
    "Bio Technology",
    "Business Process Services",
    "Chemical Engineering",
    "Chemistry",
    "Civil Engineering",
    "Cognitive Science",
    "Computer Application",
    "Computer Science",
    "Computer Science Engineering",
    "Computer Science Engineering(Cyber)",
    "Computer Technology",
    "Electrical & Electronics Engineering",
    "Electronics & Communication Engineering",
    "English Literature",
    "Food Technology",
    "General",
    "Information Technology",
    "Interior Design",
    "Mathematics",
    "Mechanical Engineering",
    "Microbiology",
    "Pharmacy",
    "Physics",
    "Power Electronics and Drives",
    "Power System Engineering",
    "Professional Accounting",
    "Structural Engineering",
    "Structural Engineering (Part Time)",
    "VLSI",
    "Water Resources And Environmental Engineering",
  ],
};
